# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Study/Verilog/ComputerDesign/mymips28/mymips28.cache/wt [current_project]
set_property parent.project_path D:/Study/Verilog/ComputerDesign/mymips28/mymips28.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Study/Verilog/ComputerDesign/mymips28/mymips28.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/Alu.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/Compare.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/ControlUnit.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/Counter.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/Display.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/Divider.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/EnablePC.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/LedData.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/Mux.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/PC.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/Ram.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/Reg.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/RegFile.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/Rom.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/SignExt.v
  D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/sources_1/imports/MIPS24/MipsCPU_Top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/constrs_1/imports/ComputerDesign/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/Study/Verilog/ComputerDesign/mymips28/mymips28.srcs/constrs_1/imports/ComputerDesign/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top MipsCPU_Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MipsCPU_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MipsCPU_Top_utilization_synth.rpt -pb MipsCPU_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
